spring:
  data:
    mongodb:
      uri: mongodb+srv://manuraj0642:l4jMctLwoCR3Dw6U@cluster0.qvcxx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: JournelDB
      auto-index-creation: true
    redis:
#      uri:redis-cli -u redis://default:SEpLtoKoh7RqfQ9roXbAeILpmWxKdfp1@redis-13616.c301.ap-south-1-1.ec2.redns.redis-cloud.com:13616
      host: redis-13616.c301.ap-south-1-1.ec2.redns.redis-cloud.com
      port: 13616
      username: default
      password: SEpLtoKoh7RqfQ9roXbAeILpmWxKdfp1
  kafka:
    bootstrap-servers:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.JournelApp.JournelApp.Model;
    properties:
      security:
        protocol: SASL_SSL
        sasl:
          mechanism: PLAIN
          jaas:
            config: org.apache.kafka.common.security.scram.ScramLoginModule required username="manuraj" password="manuraj@123";
        session:
          timeout:
            ms: 30000


server:
  port: 8080
  servlet:
    context-path: /journalApp