spring:
  data:
    mongodb:
      uri: mongodb+srv://manuraj0642:l4jMctLwoCR3Dw6U@cluster0.qvcxx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: JournelDB
      auto-index-creation: true
    redis:
#      uri:redis-cli -u redis://default:SEpLtoKoh7RqfQ9roXbAeILpmWxKdfp1@redis-13616.c301.ap-south-1-1.ec2.redns.redis-cloud.com:13616
      host: redis-13616.c301.ap-south-1-1.ec2.redns.redis-cloud.com
      port: 13616
      username: default
      password: SEpLtoKoh7RqfQ9roXbAeILpmWxKdfp1


server:
  port: 8080
  servlet:
    context-path: /journalApp