pipeline {
    agent any

    tools {
        maven 'apache-maven-3.8.8'   // 👈 match exact name
        jdk 'jdk21'                  // 👈 match exact name
    }

    environment {
        SPRING_PROFILES_ACTIVE = 'docker'
    }

    stages {
        stage('Clone Code') {
            steps {
                git url: 'https://github.com/manuraj23/Journal-App.git', branch: 'main'
            }
        }

        stage('Build with Maven') {
            steps {
                bat 'mvn clean package -DskipTests'
            }
        }

        stage('Run Tests') {
            steps {
                bat 'mvn test'
            }
        }

        stage('Docker Build') {
            steps {
                bat 'docker build -t journal-app .'
            }
        }

        stage('Docker Run') {
            steps {
                bat 'docker-compose -f docker-compose.yml up -d'
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed.'
        }
    }
}
