pipeline {
    agent any

    tools {
        maven 'Maven 3.9.6'   // Make sure this version is configured in Jenkins tools
        jdk 'Java 21'         // Setup Java 21 in Jenkins tools
    }

    environment {
        SPRING_PROFILES_ACTIVE = 'docker'
    }

    stages {
        stage('Clone Code') {
            steps {
                git url: 'https://github.com/manuraj23/Journal-App.git', branch: 'main'
            }
        }

        stage('Build with Maven') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t journal-app .'
            }
        }

        stage('Docker Run') {
            steps {
                sh 'docker-compose -f docker-compose.yml up -d'
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed.'
        }
    }
}
