pipeline {
    agent any

    tools {
        maven 'apache-maven-3.8.8'
        jdk 'jdk21'
    }

    environment {
        SPRING_PROFILES_ACTIVE = 'docker'
    }

    stages {
        stage('Clone Code') {
            steps {
                git url: 'https://github.com/manuraj23/Journal-App.git', branch: 'main'
            }
        }

        stage('Build with Maven') {
            steps {
                dir('Projects/JournelApp') { // 👈 pom.xml is here
                    bat 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('Projects/JournelApp') {
                    bat 'mvn test'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('Projects/JournelApp') {
                    bat 'docker build -t journal-app .'
                }
            }
        }

        stage('Docker Run') {
            steps {
                dir('Projects/JournelApp') {
                    bat 'docker-compose -f docker-compose.yml up -d'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed.'
        }
    }
}
